export const GET_ALL_RECORD_DOCTORS="GET_ALL_RECORD_DOCTORS";
export const GET_ALL_RECORD_CERTIFICATION="GET_ALL_RECORD_CERTIFICATION";
export const CHOOSE_RECORD_DOCTOR="CHOOSE_RECORD_DOCTOR";
export const CHOOSE_RECORD="CHOOSE_RECORD";

